name: 自定义问题
description: 描述您的问题。
title: "[Other]: "
body:
    - type: textarea
      id: issue-description
      attributes:
          label: 问题描述
          description: 请描述您的问题。
      validations:
          required: true
